config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :tags
  resources :snapshots

  resources :links do
    resources :tags
  end
  
  root 'links#index'

end

app/models/link.rb
require 'openssl'
require 'base32'

class Link < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :tags
  has_many :snapshots

  def jothash
    # d = hmac.new(HMAC_KEY, url, hashlib.md5).digest()
    hmac = OpenSSL::HMAC.new('Jotmuch', OpenSSL::Digest.new('md5'))
    hmac << url

    # padding is always '======', so drop it:
    # return base64.b32encode(d).lower()[:-6]
    Base32.encode(hmac.digest)[0..-7].downcase
  end

  def mhtml
    path = Path["~/.jotmuch/archives/#{jothash}.mhtml"]
    path.exists? ? path : nil
  end

  def latest_snapshot
    snapshots.order(:created_at).last
  end
end

app/models/snapshot.rb
class Snapshot < ActiveRecord::Base
  belongs_to :link
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :links, counter_cache: true

  def inspect
    "<#{name} (#{links_count})>"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :links
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method def current_user
    User.first
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def index
    page_size = 20

    if params[:tag] and @tag = Tag.find_by(name: params[:tag])
      @links = @tag.links
    else
      @links = current_user.links
    end

    if @query = params[:search]
      @links = @links.where("LOWER(title) LIKE ? OR LOWER(description) LIKE ?", *["%#{@query.downcase}%"]*2)
    end

    @links = @links.limit(page_size).offset(current_page * page_size).includes(:tags)
  end

  helper_method def current_page(delta=0)
    if page_num = params[:page]
      n = page_num.to_i
    else
      n = 0
    end

    [n + delta, 0].max
  end
end

app/controllers/snapshots_controller.rb
class SnapshotsController < ApplicationController

  def show
    link = Link.find(params[:id])
    if link.mhtml
      # render file: link.mhtml, content_type: "multipart/related"
      render file: link.mhtml, content_type: "application/x-mimearchive"
    else
      render text: "Not found"
    end
  end
  
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def show
    @tag = Tag.find params[:id]
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/snapshots_helper.rb
module SnapshotsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Linx</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/links/_link.html.haml
.link
  %span.date= link.created_at.strftime("%Y-%m-%d @ %l%P")
  %span.title= link_to highlight(link.title, @query), link.url
  - buttons = [ (link_to("cached", snapshot_path(link)) if link.mhtml) , link_to("archive.org", "http://web.archive.org/#{link.url}") ]
  ( #{buttons.compact.join(" | ").html_safe} )

  .details
    .desc= highlight(link.description, @query)
    .tags
      - link.tags.each do |tag|
        %span.tag= link_to tag.name, "?tag=#{tag.name}"

  

app/views/links/index.html.haml
%h3 #{current_user.links.count} links

- if @tag
  %h1 
    TAG: #{@tag.name}

= render @links

.pager
  = link_to "< < prev", "?page=#{current_page(-1)}"
  = link_to "next > >", "?page=#{current_page(+1)}"

.search
  %form{method: "get"}
    = text_field_tag "search", @query, placeholder: "Search"